path: ../Trabajo_Fin_de_Grado/leavesDetection/data/dataset

# ruta donde estan las imagenes con las que pondremos a YOLO a entrenar
train: images
# ruta donde estan las imagenes que usará YOLO para validar el entrenamiento
val: images

#para que se mezclen imagenes durante el entrenamiento y así mejorar la capacidad de generalización del modelo
mosaic: 1.0

# numero de clases
nc: 1

# nombres de la clase
names: ['hoja']